# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-10.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/jonathanpoon/Documents/UC Davis/ecs175/4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/jonathanpoon/Documents/UC Davis/ecs175/4"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-10.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jonathanpoon/Documents/UC Davis/ecs175/4/CMakeFiles" "/Users/jonathanpoon/Documents/UC Davis/ecs175/4/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jonathanpoon/Documents/UC Davis/ecs175/4/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assignment4.x

# Build rule for target.
assignment4.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assignment4.x
.PHONY : assignment4.x

# fast build rule for target.
assignment4.x/fast:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/build
.PHONY : assignment4.x/fast

MilkshapeModel.o: MilkshapeModel.cpp.o
.PHONY : MilkshapeModel.o

# target to build an object file
MilkshapeModel.cpp.o:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/MilkshapeModel.cpp.o
.PHONY : MilkshapeModel.cpp.o

MilkshapeModel.i: MilkshapeModel.cpp.i
.PHONY : MilkshapeModel.i

# target to preprocess a source file
MilkshapeModel.cpp.i:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/MilkshapeModel.cpp.i
.PHONY : MilkshapeModel.cpp.i

MilkshapeModel.s: MilkshapeModel.cpp.s
.PHONY : MilkshapeModel.s

# target to generate assembly for a file
MilkshapeModel.cpp.s:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/MilkshapeModel.cpp.s
.PHONY : MilkshapeModel.cpp.s

Model.o: Model.cpp.o
.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i
.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s
.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/Model.cpp.s
.PHONY : Model.cpp.s

car.o: car.cpp.o
.PHONY : car.o

# target to build an object file
car.cpp.o:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/car.cpp.o
.PHONY : car.cpp.o

car.i: car.cpp.i
.PHONY : car.i

# target to preprocess a source file
car.cpp.i:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/car.cpp.i
.PHONY : car.cpp.i

car.s: car.cpp.s
.PHONY : car.s

# target to generate assembly for a file
car.cpp.s:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/car.cpp.s
.PHONY : car.cpp.s

draw.o: draw.cpp.o
.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i
.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s
.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/draw.cpp.s
.PHONY : draw.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/assignment4.x.dir/build.make CMakeFiles/assignment4.x.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... assignment4.x"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MilkshapeModel.o"
	@echo "... MilkshapeModel.i"
	@echo "... MilkshapeModel.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... car.o"
	@echo "... car.i"
	@echo "... car.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

